model_selection:
  model:
    XGBClassifier:
      search_param_grid:
        learning_rate: [0.01, 0.1, 0.2]
        max_depth: [3, 5, 7]
    GradientBoostingClassifier:
      search_param_grid:
        learning_rate: [0.01, 0.1, 0.2]
        n_estimators: [100, 200, 300]
    SVC:
      search_param_grid:
        C: [0.1, 1, 10]
        kernel: ['linear', 'rbf']
    RandomForestClassifier:
      search_param_grid:
        n_estimators: [100, 200, 300]
        max_features: ['auto', 'sqrt', 'log2']